[Feat] 묻고 답하기 카테고리별 정렬 및 추천순 조회순 정렬 완료 #12
Likelion-lucky7/DECO pull request #114
Opened 2023-03-26 13:29 UTC by lulla-by

## ✨ 구현 기능 명세
- 카테고리별 정렬 및 추천순 조회순 정렬 완료

## 🕰 소요시간
- 5시간

## 😭 어려웠던 점
- 리코일로 전역state를 변경하기 위해서 selector의 set을 사용했었습니다. 하지만 그로인해 새로고침이 발생하게 되었고 이후에 useState를 사용하여 조건부 렌더링을 진행하니 새로고침없이 렌더링되는것을 확인했습니다. 리코일에 과하게 집착해서 시간이 더 늦어진것같습니다...
- 또한 추천순 및 최신순 정렬시 깊은복사를 하지않고 전역state를 그대로 처리하니 수정된 데이터내에서만 정렬이 진행되어 기능이 정상적으로 작동하지 않았습니다. 이를 해결하기 위해 spered operator를 사용하여 깊은 복사를 진행한뒤 원본데이터를 참조하여 추천순 및 최신순으로 렌더링 되도록 작업했습니다.

2023-03-26 16:12 UTC, realldk requested changes
setFilterdData -> setFilteredData 이거 말씀드린거였어요

2023-03-26 16:12 UTC, realldk commented on deco/src/components/QuestionPage/QuestionList.jsx
> +  let [filteredData, setFilterdData] = useState([...originalData]);
setFilterdData -> setFilteredData 여기랑 밑에 똑같은 것들 말씀드린 거였는데 restprops에도 오타가 있었나보네요ㅎㅎ; 그리고 issue close하지 않고 commit, push 다시 하시면 pr이 자동 최신화됩니다.

2023-03-27 00:24 UTC, lulla-by commented on deco/src/components/QuestionPage/QuestionList.jsx
> +  let [filteredData, setFilterdData] = useState([...originalData]);
네 수정했습니다~

2023-03-27 00:25 UTC, realldk approved these changes
굿굿

2023-03-27 00:26 UTC, HJY0 approved these changes
수고하셨습니다!

2023-03-27 00:27 UTC, merged